import {getAllProductsDescriptions}from"./module/productDescription.js";
import {getAllSanFranciscoEmployees}from"./module/employeesSanFrancisco.js";
import {getAllOrdersShipped}from"./module/shippedOrders.js";
import {getAllPaymentDetailsClient103}from"./module/paymentDetails.js";
import {getAllUsaClientsCreditLimitGreaterThan500}from"./module/clientsFromUsa.js";
import{getAllProductsNextToDescriptions}from"./module/productsLineDescription.js";
import{getAllNamesAddresEmailsEmployees}from"./module/nameAddresEmail.js";
import{getAllOrdersMadeFromFrance}from"./module/ordersFromFrance.js";
import{getAllPaymentsReceivedOfEachClient}from"./module/paymentsReceived.js";
import{getAllOrderDetailsProductNamesyClient101}from"./module/ordersProductNameClient.js";
import{getAllAveragesCreditLimitOfClients}from"./module/averageCreditLimit.js";
import{getAllQuantityInStock}from"./module/totalStock.js";
import{getAllProductsAverage}from"./module/averageBuyPrice.js";
import{getAllOfficesQuantityByCountry}from"./module/officesQuantityByCountry.js";
import{getAllPaymentsRecieved}from"./module/totalPayments.js";
import{getAllEmployeeQuantity}from"./module/quantityOfEmployees.js";
import{getAllOrdersAverage}from"./module/averageOrderedNumber.js";
import{getAllProductsPriece}from"./module/totalPriceProducts.js";
import{getAllMSRPAverage}from"./module/msrpAverage.js";
import{getAllEmployeesTitleJob}from"./module/quantityEmployeesJobTitle.js";
import{getAllPaymentsRecievedByEachClient}from"./module/paysReceivedByClients.js";
import{getAllAverageCreditByCountry}from"./module/averageCrditLimitByCuntry.js";
import{getAllOrdersMadeByEachClient}from"./module/ordersNumberByClient.js";
import{getAllProductsOrderedByEachClient}from"./module/quantityOfProductsOrdered.js";
import{getAllSalesSortedByPrice}from"./module/salesTotalOrderedByPrice.js";
import{getAllProductInStockAverage}from"./module/averageOfProductsInStock.js";
import{getAllPaymentsMadeByCountry}from"./module/totalOfPaymentsByCountry.js";
import{getAllSalesAverageSortedByPriceForEachEmployee}from"./module/averageOfSalesByEmployees.js";
import{getAllOrdersMadeForEachEmployee}from"./module/ordersMadeByEmployees.js";
import{getAllProductsSoldAndProductLine}from"./module/quantityOfProductsSoldPl.js";
console.log(await getAllProductsSoldAndProductLine());