import {getAllProductsDescriptions}from"./module/descriptionProduct.js";
import {getAllSanFranciscoEmployees}from"./module/employeessanfrancisco.js";
import {getAllOrdersShipped}from"./module/shippedorder.js";
import {getAllPaymentDetailsClient103}from"./module/paymentdetails.js";
import {getAllUsaClientsCreditLimitGreaterThan500}from"./module/clientsusa.js";
import{getAllProductsNextToDescriptions}from"./module/productslinedesc.js";
import{getAllNamesAddresEmailsEmployees}from"./module/nameaddresemail.js";
import{getAllOrdersMadeFromFrance}from"./module/orderfromfrance.js";
import{getAllPaymentsReceivedOfEachClient}from"./module/paymentsreceived.js";
import{getAllOrderDetailsProductNamesyClient101}from"./module/ordersproductnameclient.js";
console.log(await getAllOrderDetailsProductNamesyClient101());